# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.define "client" do |client|
  	client.vm.provider :virtualbox do |vb|
		vb.customize [ 'modifyvm', :id, '--memory', '386' ]
		vb.customize [ 'modifyvm', :id, '--cpus', '1' ]
		vb.customize [ 'modifyvm', :id, '--name', 'client' ]
  	end
  	client.vm.network "private_network", ip: "192.168.56.100"
	client.vm.hostname = "client"
	client.vm.provision "shell", path: "script_cliente.sh"
  end
  config.vm.define "server" do |server|
  	server.vm.box = "ubuntu/focal64"
  	server.vm.provider :virtualbox do |vb|
		vb.customize [ 'modifyvm', :id, '--memory', '512' ]
		vb.customize [ 'modifyvm', :id, '--cpus', '2' ]
		vb.customize [ 'modifyvm', :id, '--name', 'server' ]
  	end
	server.vm.network "private_network", ip: "192.168.56.50"
	server.vm.hostname = "server"
	server.vm.provision "shell", path: "script_server.sh"
  end
end
