# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.define "client" do |client|
  	client.vm.provider :virtualbox do |vb|
		vb.customize [ 'modifyvm', :id, '--memory', '386' ]
		vb.customize [ 'modifyvm', :id, '--cpus', '1' ]
		vb.customize [ 'modifyvm', :id, '--name', 'client' ]
  	end
  	client.vm.network "private_network", ip: "192.168.56.1"
	client.vm.hostname = "client"
	client.vm.provision "shell", inline: <<-SHELL
		cp /vagrant/cliente.py /home/vagrant/
		sed -i 's/\r$//' /home/vagrant/cliente.py
  	SHELL
  end
  config.vm.define "server" do |server|
  	server.vm.box = "ubuntu/focal64"
  	server.vm.provider :virtualbox do |vb|
		vb.customize [ 'modifyvm', :id, '--memory', '512' ]
		vb.customize [ 'modifyvm', :id, '--cpus', '2' ]
		vb.customize [ 'modifyvm', :id, '--name', 'server' ]
  	end
	server.vm.network "private_network", ip: "192.168.56.2"
	server.vm.hostname = "server"
	server.vm.provision "shell", inline: <<-SHELL
		cp /vagrant/server.py /home/vagrant/
		sed -i 's/\r$//' /home/vagrant/server.py
  	SHELL
  end
end